name: Build elpa
on:
  schedule:
    - cron: '20 2 * * *'
  push:
    branches: main
  workflow_dispatch:
jobs:
  build:
    name: Build elpa
    runs-on: ubuntu-26.04
    permissions:
      contents: write
    steps:
      - name: Fetch recipes
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Cache sources
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: sources
          path: sources
      - name: Build elpa
        uses: melpa/package-build@f19a7f58cf4b2e573a6d551d8d3dbe265c2566b4 # v5
        env:
          ELPA_NAME: Lelpa
          ELPA_STEM: lelpa
          ELPA_URL: https://luciuschen.github.io/Lelpa/
          REPO_URL: https://github.com/LuciusChen/Lelpa
          WIKI_URL: ${{ github.event.repository.html_url }}/wiki
        with:
          args: build-channels page
      - name: Deploy elpa
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          sudo chown -R "$(id -u):$(id -g)" archives
          cd archives
          git init
          git checkout -b gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy Lelpa archive"
          git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" gh-pages
